# Generated by Django 2.1.5 on 2020-06-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ベビーカー入店可能'), (2, 'ベビーチェア有り'), (3, 'ソファー席あり'), (4, 'キッズメニューあり'), (5, 'おむつ交換台あり'), (6, '離乳食持ち込み可')], default='3', verbose_name='レビュースコア'),
        ),
    ]
