# Generated by Django 2.1.5 on 2020-06-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0004_auto_20200624_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='info',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ベビーカー入店可能'), (2, 'ベビーチェア有り'), (3, 'ソファー席あり'), (4, 'キッズメニューあり'), (5, 'おむつ交換台あり'), (6, '離乳食持ち込み可')], default='3', verbose_name='子連れ情報'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default='3', verbose_name='レビュースコア'),
        ),
    ]
