# Generated by Django 3.0.7 on 2020-11-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0006_auto_20201104_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='babycar_info',
            field=models.PositiveSmallIntegerField(choices=[[0, 'ベビーカー入店不可'], [1, 'ベビーカー入店可能']], default='0', verbose_name='ベビーカー情報'),
        ),
    ]
