# Generated by Django 3.0.7 on 2020-11-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0007_auto_20201104_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='babychair_info',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ベビーチェア有り'), (1, 'ベビーチェア無し')], default='0', verbose_name='ベビーチェア情報'),
        ),
        migrations.AlterModelTable(
            name='review',
            table='Reviews',
        ),
    ]
